/*
 * Project: TGTGamer
 * File: 392_is_subsequence.spec.ts
 * Last Modified: 2026-09-25
 *
 * Contributing: Please read through our contributing guidelines. Included are directions for opening issues, coding standards,
 * and notes on development. These can be found at
 * https://github.com/TGTGamer/TGTGamer/blob/main/CONTRIBUTING.md
 *
 * Code of Conduct: This project abides by the Contributor Covenant, v2.0. Please interact in ways that contribute to an open,
 * welcoming, diverse, inclusive, and healthy community. Our Code of Conduct can be found at
 * https://github.com/TGTGamer/TGTGamer/blob/main/CODE_OF_CONDUCT.md
 *
 * Copyright (c) 2026 Jonathan Stevens T/A Resnovas. All Rights Reserved
 * LICENSE: Fair Core License, Version 1.0, MIT Future License (FCL-1.0-MIT)
 *
 * This program has been provided under confidence of the copyright holder and is licensed for copying, distribution and
 * modification under the terms of the Fair Core License, Version 1.0, MIT Future License (FCL-1.0-MIT) published as the License, or
 * (at your option) any later version of this license. You must not move, change, disable, or circumvent the license key functionality
 * in the Software; or modify any portion of the Software protected by the license key to: enable access to the protected
 * functionality without a valid license key; or remove the protected functionality. This program is distributed in the hope that it
 * will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the Fair Core License, Version 1.0, MIT Future License for more details. You should have received a
 * copy of the Fair Core License, Version 1.0, MIT Future License along with this program. If not, please write to:
 * hello@resnovas.com, see the official website https://fcl.dev/ or review the GitHub repository
 * https://github.com/keygen-sh/fcl.dev/
 *
 * This project abides the Resnovas Cooperation Commitment. Adapted from the GPL Cooperation Commitment (GPLCC). Before filing
 * or continuing to prosecute any legal proceeding or claim (other than a Defensive Action) arising from termination of a Covered
 * License, we commit to adhering to the Resnovas Cooperation Commitment. You should have received a copy of the Resnovas
 * Cooperation Commitment along with this program. If not, please write to: hello@resnovas.com, or see
 * https://github.com/TGTGamer/TGTGamer/blob/main/COOPERATION_COMMITMENT.md
 *
 * DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE
 */

import { describe, expect, it } from "vitest"
import { IsSubsequence } from "../../../packages/leetcode/src/392_is_subsequence.js";

// Generated by CodiumAI

describe('IsSubsequence', () => {

    // Returns true when s is an empty string
    it('should return true when s is an empty string', () => {
      // Given an empty string s
      const s = '';
      // And a non-empty string t
      const t = 'abcde';
  
      // When we invoke the IsSubsequence function with s and t
      const result = IsSubsequence(s, t);
  
      // Then the result should be true
      expect(result).toBe(true);
    });

    // Returns true when s is a single character and exists in t
    it('should return true when s is a single character and exists in t', () => {
      // Given a single character string s that exists in t
      const s = 'a';
      const t = 'abcde';
  
      // When we invoke the IsSubsequence function with s and t
      const result = IsSubsequence(s, t);
  
      // Then the result should be true
      expect(result).toBe(true);
    });

    // Returns true when s is a substring of t
    it('should return true when s is a substring of t', () => {
      // Given a string s that is a substring of t
      const s = 'abc';
      const t = 'abcdefg';
  
      // When we invoke the IsSubsequence function with s and t
      const result = IsSubsequence(s, t);
  
      // Then the result should be true
      expect(result).toBe(true);
    });

    // Returns true when s is equal to t
    it('should return true when s is equal to t', () => {
      // Given a string s that is equal to t
      const s = 'abcde';
      const t = 'abcde';
  
      // When we invoke the IsSubsequence function with s and t
      const result = IsSubsequence(s, t);
  
      // Then the result should be true
      expect(result).toBe(true);
    });

    // Returns true when s is a subsequence of t
    it('should return true when s is a subsequence of t', () => {
      // Given a string s that is a subsequence of t
      const s = 'ace';
      const t = 'abcdefg';
  
      // When we invoke the IsSubsequence function with s and t
      const result = IsSubsequence(s, t);
  
      // Then the result should be true
      expect(result).toBe(true);
    });

    // Returns false when s is not a substring of t
    it('should return false when s is not a substring of t', () => {
      // Given a string s that is not a substring of t
      const s = 'xyz';
      const t = 'abcdefg';
  
      // When we invoke the IsSubsequence function with s and t
      const result = IsSubsequence(s, t);
  
      // Then the result should be false
      expect(result).toBe(false);
    });

    // Returns false when s is longer than t
    it('should return false when s is longer than t', () => {
      // Given a string s that is longer than t
      const s = 'abcdefg';
      const t = 'abc';
  
      // When we invoke the IsSubsequence function with s and t
      const result = IsSubsequence(s, t);
  
      // Then the result should be false
      expect(result).toBe(false);
    });

    // Returns false when s is empty and t is not
    // Expectation corrected: the empty string is a subsequence of every string (LeetCode 392).
    it('should return true when s is empty and t is not', () => {
      // Given an empty string s and a non-empty string t
      const s = '';
      const t = 'abcde';
  
      // When we invoke the IsSubsequence function with s and t
      const result = IsSubsequence(s, t);
  
      // Then the result should be false
      expect(result).toBe(true);
    });

    // Returns false when s is not a subsequence of t
    // Expectation corrected: "acd" is a subsequence of "abcdefg" (a, c and d appear in order).
    it('should return true when s is a subsequence of t', () => {
      // Given a string s that is not a subsequence of t
      const s = 'acd';
      const t = 'abcdefg';
  
      // When we invoke the IsSubsequence function with s and t
      const result = IsSubsequence(s, t);
  
      // Then the result should be false
      expect(result).toBe(true);
    });

    // Returns true when s is a single character and does not exist in t
    // Expectation corrected: "x" does not occur in "abcde", so it cannot be a subsequence.
    it('should return false when s is a single character and does not exist in t', () => {
      // Given a single character string s that does not exist in t
      const s = 'x';
      const t = 'abcde';
  
      // When we invoke the IsSubsequence function with s and t
      const result = IsSubsequence(s, t);
  
      // Then the result should be true
      expect(result).toBe(false);
    });

    // Returns true when s is a single character and exists multiple times in t
    it('should return true when s is a single character and exists multiple times in t', () => {
      // Given a single character string s that exists multiple times in t
      const s = 'a';
      const t = 'abcdeade';
  
      // When we invoke the IsSubsequence function with s and t
      const result = IsSubsequence(s, t);
  
      // Then the result should be true
      expect(result).toBe(true);
    });

    // Returns true when s is a substring of t, but not a subsequence
    it('should return true when s is a substring of t, but not a subsequence', () => {
      // Given a string s that is a substring of t, but not a subsequence
      const s = 'abc';
      const t = 'abdcdefg';
  
      // When we invoke the IsSubsequence function with s and t
      const result = IsSubsequence(s, t);
  
      // Then the result should be true
      expect(result).toBe(true);
    });
});
