name: Update Readme - blog

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:  
  update-blog:
    name: Update Readme with blogs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: 100
          feed_list: 'http://stackoverflow.com/feeds/user/7988421'
