name: Update Readme - blog

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:  
  update-blog:
    name: Update Readme with blogs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'http://jonathanstevens.org/news/feed/, 	https://stackoverflow.com/feeds/user/7988421'
