###
 # @format
 # -----
 # Project: TGTGamer
 # File: metrics.yml
 # Path: \.github\workflows\metrics.yml
 # Created Date: Tuesday, December 12th 2023
 # Author: Jonathan Stevens (Email: jonathan@resnovas.com, Github: https://github.com/TGTGamer)
 # -----
 # Contributing: Please read through our contributing guidelines. Included are directions for opening
 # issues, coding standards, and notes on development. These can be found at https://github.com/TGTGamer/blob/develop/CONTRIBUTING.md
 #
 # Code of Conduct: This project abides by the Contributor Covenant, version 2.0. Please interact in ways that contribute to an open,
 # welcoming, diverse, inclusive, and healthy community. Our Code of Conduct can be found at https://github.com/TGTGamer/blob/develop/CODE_OF_CONDUCT.md
 # -----
 # Copyright (c) 2023 - 2024 Resnovas - All Rights Reserved
 # LICENSE: Creative Commons Zero v1.0 Universal (CC0-1.0)
 # -----
 # This program has been provided under confidence of the copyright holder and is 
 # licensed for copying, distribution and modification under the terms of
 # the Creative Commons Zero v1.0 Universal (CC0-1.0) published as the License,
 # or (at your option) any later version of this license.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # Creative Commons Zero v1.0 Universal for more details.
 #
 # You should have received a copy of the Creative Commons Zero v1.0 Universal
 # along with this program. If not, please write to: jonathan@resnovas.com,
 # or see https://creativecommons.org/publicdomain/zero/1.0/legalcode
 #
 # DELETING THIS NOTICE AUTOMATICALLY VOIDS YOUR LICENSE - PLEASE SEE THE LICENSE FILE FOR DETAILS
 # -----
 # Last Modified: Wed Jan 17 2024
 # By: Jonathan Stevens (Email: jonathan@resnovas.com, Github: https://github.com/TGTGamer)
 ###

# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 */4 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

permissions:
  contents: read

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            games/github-snake.svg
            games/github-snake-dark.svg?palette=github-dark

      # commit the output files back to the repo using a personal access token
      - name: Commit files
        uses: EndBug/add-and-commit@v7
        with:
          add: "games/"
          push: true

      - uses: lowlighter/metrics@latest
        with:
          use_prebuilt_image: true
          token: ${{ secrets.ACCESS_TOKEN }}
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: true
          base_indepth: true
          config_display: large
          config_timezone: Europe/London
          plugin_stars: true
          plugin_stars_limit: 4
          repositories_forks: true
          filename: metrics/section-intro.*

      - uses: lowlighter/metrics@latest
        with:
          use_prebuilt_image: true
          token: ${{ secrets.ACCESS_TOKEN }}
          template: classic
          filename: metrics/section-followup.*
          base: ""
          base_skip: true
          config_timezone: Europe/London
          plugin_followup: true
          plugin_followup_archived: true
          plugin_followup_indepth: true
          plugin_followup_sections: repositories
          repositories_forks: true

      - uses: lowlighter/metrics@latest
        with:
          use_prebuilt_image: true
          token: ${{ secrets.ACCESS_TOKEN }}
          template: classic
          filename: metrics/section-habbits.*
          base: ""
          base_skip: true
          config_display: large
          config_timezone: Europe/London
          plugin_habits: true
          plugin_habits_charts: true
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: true
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: true
          repositories_forks: true

      - uses: lowlighter/metrics@latest
        with:
          use_prebuilt_image: true
          token: ${{ secrets.ACCESS_TOKEN }}
          template: classic
          filename: metrics/section-isocalendar.*
          base: ""
          base_skip: true
          config_display: large
          config_timezone: Europe/London
          plugin_isocalendar: true
          plugin_isocalendar_duration: full-year
          repositories_forks: true

      - uses: lowlighter/metrics@latest
        with:
          use_prebuilt_image: true
          token: ${{ secrets.ACCESS_TOKEN }}
          template: classic
          filename: metrics/section-languages.*
          base: ""
          base_skip: true
          config_display: large
          config_timezone: Europe/London
          plugin_languages: true
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: true
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          repositories_forks: true

      - uses: lowlighter/metrics@latest
        with:
          use_prebuilt_image: true
          token: ${{ secrets.ACCESS_TOKEN }}
          template: classic
          filename: metrics/section-sponsors.*
          base: ""
          base_skip: true
          config_timezone: Europe/London
          plugin_sponsors: true
          plugin_sponsors_past: true
          plugin_sponsors_sections: goal, list, about
          plugin_sponsors_size: 24
          plugin_sponsors_title: Sponsor Me!
          repositories_forks: true

      - uses: lowlighter/metrics@latest
        with:
          use_prebuilt_image: true
          token: ${{ secrets.ACCESS_TOKEN }}
          template: classic
          filename: metrics/section-leetcode.*
          base: ""
          base_skip: true
          config_timezone: Europe/London
          plugin_leetcode: true
          plugin_leetcode_limit_recent: 6
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved, skills, recent
          plugin_leetcode_user: tgtgam3r
          repositories_forks: true

      - uses: lowlighter/metrics@latest
        with:
          use_prebuilt_image: true
          token: ${{ secrets.ACCESS_TOKEN }}
          template: classic
          filename: metrics/section-code.*
          base: ""
          base_skip: true
          config_timezone: Europe/London
          plugin_code: true
          plugin_code_days: 3
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_visibility: public
          repositories_forks: true

      - uses: lowlighter/metrics@latest
        with:
          use_prebuilt_image: true
          token: ${{ secrets.ACCESS_TOKEN }}
          template: classic
          filename: metrics/section-achievements.*
          base: ""
          base_skip: true
          config_timezone: Europe/London
          config_display: large
          plugin_achievements: true
          plugin_achievements_display: detailed
          plugin_achievements_secrets: true
          plugin_achievements_threshold: C
          repositories_forks: true
